"""Add active column to products

Revision ID: 425a40a2a5a1
Revises: a0fa9395d49b
Create Date: 2025-12-12 02:45:26.438123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425a40a2a5a1'
down_revision = 'a0fa9395d49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
